
[[constraint]]
  name = "github.com/agl/ed25519"
  revision = "278e1ec8e8a6e017cd07577924d6766039146ced"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-socks"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/goleveldb"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/websocket"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/winsvc"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  revision = "adab96458c51a58dc1783b3335dcce5461522e75"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/blake256"

[[constraint]]
  branch = "master"
  name = "github.com/decred/bitset"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrrpcclient"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrutil"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  revision = "48cf8722c3375517aba351d1f7577c40663a4407"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/logrotate"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "81e90905daefcd6fd217b62423c0908922eadb30"
